baseURL = "http://douglasfinlay.com/"
title = "Douglas Finlay"
theme = "hugo-coder"

languageCode = "en-gb"

[params]
    author = "Douglas Finlay"
    info = "Software Developer"
    description = "Welcome to my corner of the sky"
    keywords = ""

    avatarURL = "images/headshot.jpg"
    gravatar = "douglas@douglasfinlay.com"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    since = 2022

    colorScheme = "auto"
    hideColorSchemeToggle = false

[[params.social]]
    name = "GitHub"
    icon = "fa fa-2x fa-github"
    weight = 1
    url = "https://github.com/dougfinl"

[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-2x fa-linkedin"
    weight = 1
    url = "https://uk.linkedin.com/in/douglasfinlay"

[[params.social]]
    name = "Mail"
    icon = "fa fa-2x fa-envelope"
    weight = 1
    url = "mailto:douglas@douglasfinlay.com"

[[menu.main]]
    name = "About"
    weight = 1
    url = "about"

[[menu.main]]
    name = "Projects"
    weight = 2
    url = "projects"

[[menu.main]]
    name = "Theatre"
    weight = 3
    url = "theatre"
    